# Generated by Django 2.1.4 on 2019-01-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование периода', max_length=50)),
                ('begin_d', models.DateField(help_text='Дата начала периода')),
                ('end_d', models.DateField(help_text='Дата окончанияе периода')),
                ('comment', models.TextField(blank=True, help_text='Примечание', max_length=500, null=True)),
            ],
            options={
                'ordering': ['-begin_d'],
            },
        ),
    ]
