# Generated by Django 2.1.4 on 2019-01-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyPay', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Periods',
            new_name='Period',
        ),
    ]
